# Generated by Django 3.0.3 on 2020-03-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publicationYear',
            field=models.IntegerField(help_text='Enter year of publication of the book'),
        ),
    ]
