# Generated by Django 3.0.3 on 2020-03-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200313_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(help_text='Enter publisher of the book', max_length=200),
        ),
    ]
