# Generated by Django 3.0.3 on 2020-03-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200316_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='callNumber',
            field=models.CharField(default=123, help_text='3-digit Call Number based on the <a href="https://www.library.illinois.edu/infosci/research/guides/dewey">Dewey Decimal System</a>', max_length=3, verbose_name='Call Number'),
            preserve_default=False,
        ),
    ]
